### ISSUE TITLE
Sources still not visible

### ISSUE THREAD

**Issue by vitusortner** [xgouchet/Elmyr#15]
Even though I'm using the latest version of your library (0.8) the source code is still not visible for me, when viewing from an IDE.

**Comment by xgouchet** [comment]
The sources.jar is generated, and downloadable in the maven repository. There might be some configuration necessary to have it handled by your IDE. The fact that the sources are kotlin files and not Java might be part of the issue.

**Comment by vitusortner** [comment]
I've got it to work previously with close to the same changes you've done. Except it looks like 'sources' is missing an 's' in the `build.gradle`s sourcesJar task.

```
...
task sourcesJar(type: Jar, dependsOn: classes) {
    from sourceSets.main.allSource
    classifier = 'source'
    archiveName = 'sources.jar'
}
...
```

which should be:
```
...
task sourcesJar(type: Jar, dependsOn: classes) {
    from sourceSets.main.allSource
    classifier = 'sources'
    archiveName = 'sources.jar'
}
...
```
