### ISSUE TITLE
NoSuchFieldError: CAPITALIZED_SENTENCE

### ISSUE THREAD

**Issue by josemlechon** [xgouchet/Elmyr#55]
After updating Gradle to the 6.7.1 version the library cannot find  CAPITALIZED_SENTENCE and it crashes when executes a test. 
![Screenshot 2021-07-26 at 15 20 01](https://user-images.githubusercontent.com/16352946/126995812-4dbec936-fdf4-4300-88a6-ef4b20894ed7.png)

**Comment by xgouchet** [comment]
Hi @josemlechon, did you upgrade your version of Elmyr ? This field has been deprecated in version `1.0.0` of the library and indeed doesn't exist anymore.

**Comment by josemlechon** [comment]
Hi, 
yes, we have 1.3.0
