### ISSUE TITLE
Seems like the hosting server of Elmyr library has been shutdown

### ISSUE THREAD

**Issue by carlosmacieljrpe** [xgouchet/Elmyr#61]
Seems like this library was using https://status.bintray.com/ which has been shutdown/ Is there any way to host the library in a different place?

In order to reproduce this issue you can check this link:
https://google.bintray.com/flexbox-layout/com/github/xgouchet/Elmyr/1.3.0/Elmyr-1.3.0.pom
It is returning a 502 error

**Comment by xgouchet** [comment]
Hi this library is distributed using [Jitpack](https://jitpack.io/#xgouchet/Elmyr) (as mentioned in the README and docs). Simply add this to your `build.gradle` file to be able to use it: 
```
    repositories {
        maven { url "https://jitpack.io" }
    }
```
